name: Push to mstechcenter

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - name: Generate token
        id: generate_token
        uses: tibdex/github-app-token@v2
        with:
          app_id: ${{ secrets.BOT_4_DEV2_F_MSTECHCENTER_APP_ID }}
          private_key: ${{ secrets.BOT_4_DEV2_F_MSTECHCENTER_PRIVATE_KEY }}  
      - name: Push file 
        uses: dobbelina/multi_file_bandit@main
        env:
          API_TOKEN_GITHUB: ${{ steps.generate_token.outputs.token }}
        with:
          source_file: "/"
          destination_repo: "mstechcenter/ppfcli-4-functions-template"          
          user_email: "admin@mstechcenter.com"
          user_name: "admin-mstc"
          rsync_option: "-avr --delete --exclude .github/workflows"
    
  
